services:
  postgres:
    image: postgres:18
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=passw0rd
      - PGDATA=/data/postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - .docker/init.sql:/docker-entrypoint-initdb.d/create-schemas.sql

  keycloak:
    image: keycloak/keycloak:26.3.0
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/postgres
      KC_DB_SCHEMA: keycloak
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: passw0rd
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: passw0rd
    command: start-dev --import-realm
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - ./.docker:/opt/keycloak/data/import